**Introduction to Pandas**

In [1]:
# import pandas library
# pd is the short name used for pandas

import pandas as pd

print("Pandas imported successfully")

Pandas imported successfully

**What is pandas?**

In [4]:
# pandas is used to work with table data
# like Excel table or CSV file

print("Pandas helps us work with rows and columns")

Pandas helps us work with rows and columns

**Creating a Series**

In [5]:
# Series = one single column of data

s = pd.Series([10, 20, 30, 40, 50])

print(s)

# Series is like one column
# index is on left
# values are on right

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
# Series with custom index

# we can also give our own labels/index

s2 = pd.Series([90, 85, 88], index=["Math", "English", "Science"])

print(s2)

# custom labels make data more meaningful

Math       90
English    85
Science    88
dtype: int64

Create a DataFrame

In [7]:
# DataFrame = table with rows and columns

data = {
    "Name": ["Madhu", "Rahul", "Priya", "Arjun", "Neha"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["MSC", "BSc", "BBA", "BCA", "BSc"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

print(df)

# dictionary keys become column names
# each list becomes one column
# DataFrame is the main pandas object

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92
3  Arjun   22    BCA     74
4   Neha   20    BSc     88

In [8]:
# Check type

# type() tells what kind of object it is

print(type(df))

# this confirms it is a DataFrame

<class 'pandas.core.frame.DataFrame'>

In [9]:
# View first rows

# head() shows first 5 rows by default

df.head()

# useful for quickly checking big datasets

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92
3  Arjun   22    BCA     74
4   Neha   20    BSc     88

In [10]:
# View last rows

# tail() shows last 5 rows by default

df.tail()

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92
3  Arjun   22    BCA     74
4   Neha   20    BSc     88

In [11]:
# Column names

# columns shows all column names

df.columns

Index(['Name', 'Age', 'Course', 'Marks'], dtype='object')

In [12]:
# Basic info

# info() gives summary
# shows column names, data types, non-null values

df.info()

# very useful for understanding dataset structure

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Course  5 non-null      object
 3   Marks   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [13]:
# Statistical summary

# describe() gives summary of numerical columns

df.describe()

             Age      Marks
count   5.000000   5.000000
mean   20.400000  83.400000
std     1.140175   7.334848
min    19.000000  74.000000
25%    20.000000  78.000000
50%    20.000000  85.000000
75%    21.000000  88.000000
max    22.000000  92.000000

In [14]:
# Select one column

# select one column using column name

# df["Name"]

# Select multiple columns

# select multiple columns using list

df[["Name", "Marks"]]

    Name  Marks
0  Madhu     85
1  Rahul     78
2  Priya     92
3  Arjun     74
4   Neha     88

In [15]:
# Select a row using index

# loc is used to select row by label/index

df.loc[0]

# row 0 means first row

Name      Madhu
Age          20
Course      MSC
Marks        85
Name: 0, dtype: object

In [16]:
# Select multiple rows

# select rows 0 to 2

df.loc[0:2]

# in loc, end value is included

    Name  Age Course  Marks
0  Madhu   20    MSC     85
1  Rahul   21    BSc     78
2  Priya   19    BBA     92

In [17]:
# Select row and specific columns

# select row 1 and 2 with Name and Marks columns

df.loc[1:2, ["Name", "Marks"]]

    Name  Marks
1  Rahul     78
2  Priya     92

In [18]:
# # iloc selects by position number

df.iloc[0]

# loc = label based
# iloc = position based

Name      Madhu
Age          20
Course      MSC
Marks        85
Name: 0, dtype: object

In [19]:
# Filter data

# show students with marks greater than 80

df[df["Marks"] > 85]

# filtering means showing only matching rows

    Name  Age Course  Marks
2  Priya   19    BBA     92
4   Neha   20    BSc     88

In [20]:
# Another filter

# show students whose course is BCA

df[df["Course"] == "MSC"]

    Name  Age Course  Marks
0  Madhu   20    MSC     85

In [21]:
# Multiple conditions

# use & for AND condition
# use brackets around each condition

df[(df["Marks"] > 80) & (df["Course"] == "BSc")]

# & means both conditions must be true

   Name  Age Course  Marks
4  Neha   20    BSc     88

In [22]:
# Add a new column

# create a new column called Pass
# if marks >= 80 then pass = Yes else No

df["Pass"] = ["Yes", "No", "Yes", "No", "Yes"]

df

    Name  Age Course  Marks Pass
0  Madhu   20    MSC     85  Yes
1  Rahul   21    BSc     78   No
2  Priya   19    BBA     92  Yes
3  Arjun   22    BCA     74   No
4   Neha   20    BSc     88  Yes

In [23]:
# Add another calculated column

# add 5 grace marks to every student

df["Updated_Marks"] = df["Marks"] + 5

df

    Name  Age Course  Marks Pass  Updated_Marks
0  Madhu   20    MSC     85  Yes             90
1  Rahul   21    BSc     78   No             83
2  Priya   19    BBA     92  Yes             97
3  Arjun   22    BCA     74   No             79
4   Neha   20    BSc     88  Yes             93